### ISSUE TITLE
Run only for development?

### ISSUE THREAD

**Issue by zweicoder** [sindresorhus/electron-debug#28]
Is it possible to only run this in development mode?

**Comment by sindresorhus** [comment]
This module is currently not opinionated about that and it's up to you to disable it for production. I've been thinking about automating this, but not sure the best way of doing it, because as far as I know there's no convention of what's debug and release builds with Electron apps. How do you define "development mode"?

**Comment by zweicoder** [comment]
I see.. As far as I know from my limited experience with Electron there doesn't seem to be an official way to do it. I'm currently doing `NODE_ENV=dev electron .` to start the app and using `process.env.NODE_ENV` to check for the variable value. 

Will be closing this issue now as my problem is resolved!

**Comment by sindresorhus** [comment]
I'd like to keep it open as I want to look into this at some point.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/electron-debug/commit/4039271607d2c72a696a6f895406616435743d8a. Available in 0.6.0.
