### ISSUE TITLE
Not working in Electron 5.0 beta 7

### ISSUE THREAD

**Issue by hieuhlc** [sindresorhus/electron-debug#70]
I have installed `electron-debug` and `electron-react-devtools`, both latest versions.
I put this line before creating BrowserWindow in main process
```javascript
electronDebug({ showDevTools: false })
```
However I got this instead of React DevTools installed in Console

<img width="688" alt="Screen Shot 2019-03-28 at 14 11 27" src="https://user-images.githubusercontent.com/4828178/55137515-bf9f2180-5163-11e9-9141-88dcce8b52d7.png">

Please help. Thank you

**Comment by sindresorhus** [comment]
I think this is an issue in Electron v4. I haven't had time to track down why it happens.

Would probably need to add https://github.com/MarshallOfSound/electron-devtools-installer as a dependency and handle installing DevTools extensions that way instead of recommending https://github.com/firejune/electron-react-devtools (which is also outdated). The benefit would be that we could easily support many more DevTools extensions.

**Comment by sindresorhus** [comment]
@hieuhlc That's an Electron issue: https://github.com/electron/electron/issues/17586
